version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: agetaro-mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    volumes:
      - .docker/db/init.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: agetaro
      MYSQL_USER: agetaro-kun
      MYSQL_PASSWORD: tuyoi-kimochi