CREATE DATABASE IF NOT EXISTS `agetaro`;

CREATE TABLE IF NOT EXISTS `agetaro`.`users` (
    `id` BINARY(36) NOT NULL PRIMARY KEY,
    `name` VARCHAR(256) NOT NULL,
    `email` VARCHAR(256) NOT NULL UNIQUE,
    `password` VARCHAR(256) NOT NULL,
    `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;